import {
    alldocube,
    amtec,
    amtec1,
    macbook,
    audio,
    dellInspiron,
    infinixHot30,
    laptop1,
    lenovo,
    m1Bluetooth,
    technoCamon20,
    technoSpark10,
    xiomiRedmi,
    television1,
    tornado,
    vitron1,
    vitron2,
    vitron3
} from '../assets/images'

export const navLinks = [
    { label: "HOME", path: "/" },
    { label: "SHOP", path: "/shop" },    
    { label: "ABOUT", path: "/about-us" },
    { label: "CONTACT", path: "/contact-us" }
];

export const productsData = [
  {   
    _id: "vitron-htc3200s",
    imgURL: vitron3,
    brand: "Vitron",
    name: 'Vitron HTC3200S, 32"Inch Frameless Smart Android TV Netflix YouTube + FREE TVGuard + Bracket',
    price: "12,300",
    category: "television",
    description: "The Vitron HTC3200S is a 32-inch Frameless Smart Android TV that offers smart features at an incredible value. With access to Netflix, YouTube, and other streaming apps, this TV is your gateway to endless entertainment. The frameless design and HD display make it an attractive addition to any room. This package also includes a free TVGuard and wall bracket, providing extra protection and easy installation. Enjoy the convenience of smart TV features without compromising on quality or style.",
    rating: 1.5,
  },
  {
    _id: "dell-inspiron-3580",
    imgURL: dellInspiron,
    brand: "Dell",
    name: "DELL Inspiron 3580 Intel Celeron Dual Core 4205U 4GB Ram 500GB HDD 15.6 Inches",
    price: "59,999",
    category: "laptop",
    description:
      "The Dell Inspiron 3580 is a reliable and affordable laptop equipped with an Intel Celeron Dual Core 4205U processor, 4GB of RAM, and a 500GB HDD. This 15.6-inch laptop is designed for everyday tasks such as browsing the web, managing documents, and streaming media. The anti-glare LED-backlit display ensures comfortable viewing, while the robust build quality guarantees long-term durability. Ideal for students and professionals who need a dependable laptop for basic computing needs.",
    rating: 3.6,
  },
  {   
    _id: "vitron-4368fs",
    imgURL: vitron1,
    brand: "Vitron",
    name: 'Vitron 4368FS 43" Full HD Smart Android TV Netflix Youtube / 4388FS',
    price: "32,699",
    category: "television",
    description: "The Vitron 4368FS is a 43-inch Full HD Smart Android TV that brings your favorite entertainment to life. With built-in access to Netflix, YouTube, and other streaming services, you'll have endless options for movies, shows, and more. The TV's sleek design fits seamlessly into any living space, and the high-definition display offers crystal-clear picture quality. Whether you're watching your favorite series or playing games, the Vitron 4368FS delivers an immersive experience.",
    rating: 3.7,
  },
  {   
    _id: "tecno-camon-20",
    imgURL: technoCamon20,
    brand: "Tecno",
    name: 'Tecno Camon 20, 6.67", 256GB + 8GB+8GB Extended RAM, Dual SIM, 5000mAh, Predawn Black',
    price: "25,704",
    category: "phone",
    description: "The Tecno Camon 20 is a powerhouse smartphone featuring a 6.67-inch display, 256GB of internal storage, and 8GB of RAM, expandable with an additional 8GB Extended RAM. The 5000mAh battery ensures you have power throughout the day, while the Dual SIM capability offers flexibility in managing your contacts and data. The Predawn Black finish gives the phone a premium look and feel. Whether you're gaming, working, or capturing memories, the Camon 20 delivers high performance and reliability.",
    rating: 1.7,
  },
  {   
    _id: "vitron-v527",
    imgURL: audio,
    brand: "Amtec",
    name: 'Vitron V527 SubWoofer Home Theatre 2.1 With Free Headset',
    price: "6,179",
    category: "soundDevice",
    description: "The Vitron V527 Subwoofer Home Theatre System offers an immersive audio experience with a powerful subwoofer and two satellite speakers. The 2.1 setup delivers deep, resonant bass and clear, full-range sound for movies, music, and gaming. This home theatre system comes with a free headset, providing an additional option for private listening. The sleek design fits well with any home entertainment setup, and the multiple connectivity options ensure compatibility with a variety of devices. Elevate your audio experience with the Vitron V527.",
    rating: 5,
  },
  {   
    _id: "xiaomi-redmi-12c",
    imgURL: xiomiRedmi,
    brand: "Redmi",
    name: 'XIAOMI Redmi 12C, 6.71" ,3GB+64GB, 50MP, 5000mAh, 4G, Dual Sim - Graphite Grey',
    price: "13,499",
    category: "phone",
    description: "The Xiaomi Redmi 12C is an affordable yet feature-packed smartphone, boasting a large 6.71-inch display, 3GB of RAM, and 64GB of storage. The 50MP camera lets you capture stunning photos, while the 5000mAh battery ensures you stay powered up throughout the day. With 4G connectivity and Dual SIM support, this device is perfect for users who need a reliable and versatile phone without breaking the bank. The Graphite Grey color adds a sleek and modern touch.",
    rating: 2,
  },
  {   
    _id: "alldocube-i1405-gt-book",
    imgURL: alldocube,
    brand: "Alldocube",
    name: 'Alldocube I1405 GT Book Laptop 14.1", Intel Celeron N5100, 12GB RAM+256GB SSD, Type C, Windows 11',
    price: "42,000",
    category: "laptop",
    description: "The Alldocube I1405 GT Book is a compact and powerful 14.1-inch laptop featuring an Intel Celeron N5100 processor, 12GB of RAM, and a 256GB SSD for fast performance. With its sleek design and lightweight build, it's perfect for professionals and students who require portability without compromising on power. The Full HD display offers sharp and clear visuals, and the Type-C port provides versatile connectivity options. Running on Windows 11, this laptop delivers a smooth and efficient user experience.",
    rating: 4.5,
  },
  {   
    _id: "amtec-am01",
    imgURL: amtec1,
    brand: "Amtec",
    name: 'Amtec AM-01 2.1CH Multimedia Speaker BT/USB/SD/FM - Black',
    price: "5,179",
    category: "soundDevice",
    description: "The Amtec AM-01 2.1CH Multimedia Speaker System offers dynamic sound with Bluetooth, USB, SD, and FM radio capabilities. With a powerful subwoofer and two satellite speakers, it provides a full range of audio, from booming bass to clear highs. The sleek black design and compact size make it a great addition to any space. Easily connect your devices via Bluetooth or the included USB/SD ports, and enjoy your favorite music, radio stations, and more with exceptional sound quality.",
    rating: 1.4,
  },
  {   
    _id: "apple-macbook-air-mgna3ll",
    imgURL: macbook,
    brand: "Apple",
    name: "Apple MacBook Air MGNA3LL/A With Core M1 Chip 8GB RAM 512GB SSD 13.3 Inch Display (Silver)",
    price: "120,000",
    category: "laptop",
    description: "The Apple MacBook Air MGNA3LL/A is powered by the revolutionary M1 chip, offering unparalleled performance with 8GB of unified memory and 512GB of fast SSD storage. The 13.3-inch Retina display with True Tone technology provides vivid and accurate colors, making it ideal for creative professionals. This ultra-lightweight laptop is perfect for on-the-go use, with up to 18 hours of battery life, a fanless design for silent operation, and macOS Big Sur for a smooth and responsive experience.",
    rating: 3,
  },
  {   
    _id: "tecno-spark-10c",
    imgURL: technoSpark10,
    brand: "Tecno",
    name: 'Tecno Spark 10C , 6.6" FHD,128GB ROM+4GB RAM ,5000mAh,Meta Blue',
    price: "14,777",
    category: "phone",
    description: "The Tecno Spark 10C is designed for those who want more from their smartphone. With a 6.6-inch FHD display, 128GB of storage, and 4GB of RAM, this device offers smooth performance for all your apps and games. The 5000mAh battery provides extended usage time, while the Meta Blue finish gives the phone a modern and stylish look. Whether you're streaming videos, taking photos, or staying connected, the Spark 10C is up to the task.",
    rating: 5,
  },
  {   
    _id: "amtec-am017",
    imgURL: amtec,
    brand: "Amtec",
    name: 'Amtec AM-017-2.1 Speaker System 3000WATTS PMPO-BLACK',
    price: "3,179",
    category: "soundDevice",
    description: "The Amtec AM-017-2.1 Speaker System delivers powerful audio performance with a total output of 3000 watts PMPO. The system includes two satellite speakers and a subwoofer, offering rich, deep bass and clear sound for music, movies, and gaming. The sleek black design fits seamlessly into any home entertainment setup. With multiple connectivity options, including USB and AUX inputs, the AM-017 is versatile and easy to use. Enhance your audio experience with this robust and stylish speaker system.",
    rating: 5,
  },
  {   
    _id: "lenovo-ideapad-3-n4020",
    imgURL: lenovo,
    brand: "Lenovo",
    name: "Lenovo Ideapad 3 Intel Celeron N4020 4GB RAM 1TB HDD 14 Inches HD Display-Brand New",
    price: "44,999",
    category: "laptop",
    description: "The Lenovo Ideapad 3 is an excellent entry-level laptop powered by an Intel Celeron N4020 processor, 4GB of RAM, and a spacious 1TB HDD. The 14-inch HD display offers bright and clear visuals, making it suitable for both work and entertainment. This laptop is designed with portability in mind, featuring a slim profile and lightweight construction. Whether you're working on documents, watching videos, or browsing the internet, the Ideapad 3 provides reliable performance at an affordable price.",
    rating: 3.4,
  },
  {   
    _id: "infinix-hot-30i",
    imgURL: infinixHot30,
    brand: "Infinix",
    name: 'Infinix Hot 30i, 6.56", 4GB RAM, 128GB, 5000mAh, (DUAL SIM), 4G - Mirror Black',
    price: "10,000",
    category: "phone",
    description: "The Infinix Hot 30i offers an impressive combination of performance and affordability. Featuring a 6.56-inch display, 4GB of RAM, and 128GB of internal storage, this smartphone is perfect for multitasking and storing your favorite apps and media. The 5000mAh battery ensures long-lasting usage, while the dual SIM capability and 4G connectivity keep you connected wherever you go. The sleek Mirror Black finish adds a touch of style to this versatile device.",
    rating: 3,
  },
  {   
    _id: "tornado-32hdt",
    imgURL: tornado,
    brand: "Tornado",
    name: 'Tornado 32HDT - 32" HD Built-In Receiver Digital LED TV, Black',
    price: "10,000",
    category: "television",
    description: "The Tornado 32HDT is a 32-inch HD LED TV that offers excellent value for money. With a built-in receiver for digital channels, you can access a wide range of programming without needing an external decoder. The sleek black design and slim profile make this TV a great addition to any room. The HD display ensures sharp and vibrant visuals, perfect for watching movies, sports, or your favorite TV shows. Its affordable price makes it an ideal choice for budget-conscious buyers.",
    rating: 5,
  },
  {
    _id: "vitron-htc3218",
    imgURL: vitron2,
    brand: "Vitron",
    name: 'Vitron HTC3218,Frameless 32" Inch Digital LED Television USB HDMI +FREE Wall Bracket',
    price: "22,699",
    category: "television",
    description: "The Vitron HTC3218 is a stylish and compact 32-inch Digital LED TV with a frameless design that maximizes your viewing area. It comes equipped with USB and HDMI ports for easy connectivity to various devices. The TV offers clear and vibrant picture quality, making it perfect for smaller living rooms, bedrooms, or kitchens. Plus, it includes a free wall bracket, making installation a breeze. Enjoy your favorite shows, movies, and games with this versatile television.",
    rating: 4.3,
  },
]

export const footerLinks = [
    {
        title: "Products",
        links: [
            { name: "Television", path: "/televisions" },
            { name: "Phones", path: "/phones" },
            { name: "Laptops", path: "/laptops" },
            { name: "Sound Devices", path: "/sound-devices" },
        ],
    },
    {
        title: "Help",
        links: [
            { name: "About us", path: "about-us" },
            { name: "FAQs", path: "/faqs" },
            { name: "Privacy policy", path: "/privacy-policy" },
            { name: "Payment policy", path: "/payment-policy" },
        ],
    },
    {
        title: "Get in touch",
        links: [
            { name: "customer@techhaven.com", path: "mailto:mulindijrn@gmail.com" },
            { name: "+254713621330", path: "tel:+25413621330" },
        ],
    },
];


